<html>
<head></head>

<body style="background-color: gainsboro; padding: 50px;">

<div id="container" style="width:80%; margin-left: auto; margin-right: auto; margin-top: 50px; margin-bottom: 50px; padding: 50px; background-color: white;">

    <div style="text-align: center">
        <img src="cid:${cid}"/>
        <h1>Hola amigo ${userEmail}!</h1>
    </div>

    <div>
        <p>This is a paragraph. Just some text to fill the email with stuff in order to check whether is well formatted.
            It might not be, but it might be, so I need to test it with this long and nonsense text that does not give
            anyone anything useful.
        </p>
    </div>
</div>
</body>

</html>